sudo: true
language: android
jdk:
    - oraclejdk8
addons:
  apt:
    packages:
      - git
      - unzip
env:
  global:
    - secure: "p9QlO156p7auAkzxkNIRCCt95sNjRf5eHjvAU053k8eJPvWZpfZ/dJmFOc/YnDLl+Uo8zdQZQMGjCyzbp8azzFF09acLU4PHxeY4AUbMbFN0RWeI3UCISU/lzs6gIW2DD6jpL+m4uEJ0/5YfEoeNDzwNtZF0jb+OBLkkK3KSoGgSluVDEXFXbWvqxuFt+iytQLmQXSQua9s80cLpByXdulHWpSWLNvj023tsTpNEq93yVfsnxcoSuyic9VWIuQV0Eeqw85kUuoaxLCBkpre/WPJcV5g2X3kjQAcegTNJd1/iri3rTDVY/xtUKrfSGt5TfSNF8aC9CjgN0VXHMM9BkeEBfbU4neLKc5Bso5E0u7mb4m9p94B4fM9WPbkHQ1iv7adPtAkxzShadCqD5VehLUtVwTcCoPAK+jvOZ1cY+fOIugb6xznHVOWip+Om0DKIJy89SCUahVnTrP04yibuTXwjzhPrJEhwVPksGPCGtDk45yll804ltygzdSWxKphdnepBG8lPMuSyPTrYyOBJ+zVloaDJgsJddW/Rg6qwRGxOoD5reEhJeZIx35ZuFg1h4C8jaGjbIoFE/tBocGPBQceWtQzMjRGswgWIOGlmN1f9m0L8aQbEg1j3/gTXaUxmX0+euBk/LIhW/ujGcacqQADlJbBhHYcfLaHzgzSpVX8="
android:
  components:
    - platform-tools
    - build-tools-24.0.0
    - android-24
    - extra-android-m2repository
    - extra-android-support
script:
    - echo script start!
    - env
    - echo $ABC
    - echo $TRAVIS_TAG
    - echo $TRAVIS_BRANCH
after_success:
    - echo sucess